#!/usr/local/bin/perl

use Expect;

my $name;
my $group;
my $address;
my $read_community;
my $write_community;
my $uname = 'automan';
my $passwd = 'automation1';
my $prompt = '$' ;
my $confighost = 'emsu001p';
my @hostlist = (
	'nerv001p.rich1.relera.com',
	'nerv002p.denv1.relera.com',
	'nerv003p.memp1.relera.com',
	'nerv004p.lasv1.relera.com',
	'nerv005p.sana1.relera.com',
	'nerv006p.char1.relera.com',
	'nerv007p.sacr1.relera.com',
	'nerv008p.rale1.relera.com',
	'nerv009p.salt1.relera.com',
	'nerv010p.clev1.relera.com'
);
my $host;
my $homedir = '/export/home/automan';

my %group_to_type = (
        'IntCiscoSWC' => 'cisco',
        'ITCiscoSWC' => 'cisco',
        'ROCCiscoSWC' => 'cisco',
        'IntCiscoRTR' => 'cisco',
        'ITCiscoRTR' => 'cisco',
        'ROCCiscoRTR' => 'cisco',
        'IntSunSVR' => 'sun',
        'ITSunSVR' => 'sun',
        'ROCSunSVR' => 'sun',
        'NerveCenter' => 'nervecenter',
        'IntICMPOnly' => 'undefined',
        'ITICMPOnly' => 'undefined',
        'ROCICMPOnly' => 'undefined',
        'CorCiscoRTR' => 'cisco',
        'ConCiscoSWC' => 'cisco',
        'CorCiscoSWC' => 'cisco',
        'ConCiscoRTR' => 'cisco_msfc2',
        'IntSNMPGen' => 'undefined',
        'IntWaveLan' => 'wavelan',
        'ITWaveLan' => 'wavelan',
        'ROCWaveLan' => 'wavelan',
        'Mib-II' => 'undefined',
        'CacheflowD' => 'cacheflow',
        'CacheflowS' => 'cacheflow',
        'F5D' => 'f5',
        'F5S' => 'f5',
        'CorJuniperRTR' => 'juniper',
);


open CFGLIST , ">>$homedir/configarch.tmp"||die "Can't open Config export";
open CSCOLIST , ">>$homedir/ciscoworks.tmp"||die "Can't open Cisco export";
print CSCOLIST "cisco Systems NM data import,";
print CSCOLIST " source = getNodeList.pl (autogenerated);";
print CSCOLIST " Version = 2.0; Type = Csv\n";
open CSCOIPLIST , ">>$homedir/ciscoworksip.tmp"||die "Can't open Cisco export";
print CSCOIPLIST "cisco Systems NM data import,";
print CSCOIPLIST " source = getNodeList.pl (autogenerated);";
print CSCOIPLIST " Version = 2.0; Type = Csv\n";

HOST: foreach $host (@hostlist) {
  $scp = Expect->spawn("scp $uname\@$host:/opt/VRTSnc/db/nervecenter.node $homedir");
  $match = $scp->expect(30, "assword:","(yes/no)?");
  if ( $match == 1 ) {
    $scp->exp_stty('-echo');
    print $scp $passwd."\r";
    $scp->exp_stty('echo');
  }elsif( $match == 2 ) {
    print $scp "yes\r";
    $scp->expect(30, "assword");
    $scp->exp_stty('-echo');
    print $scp $passwd."\r";
    $scp->exp_stty('echo');
  }else{
    next HOST;
  }
  $name = "";
  $group = "";
  open NODES , "$homedir/nervecenter.node"||die "Can't open Node import file.";
  while ( <NODES> ) {
    chomp;
    if ($name eq "") {
      ($name) = ($_ =~ /^name (.*)$/);
    }
    if ($address eq "") {
      ($address) = ($_ =~ /^address (.*)$/);
    }
    if ($group eq "") {
      ($group) = ($_ =~ /^group (.*)$/);
    }
    if ($read_community eq "") {
      ($read_community) = ($_ =~ /^read_community (.*)$/);
    }
    if ($write_community eq "") {
      ($write_community) = ($_ =~ /^write_community (.*)$/);
    }
    if ($_ =~ /^end node$/) {
      if ( $name =~ /^prom001p.*/ ) {
        print CFGLIST "$name:quallaby\n";
      }else{
        print CFGLIST "$name:$group_to_type{$group}\n";
      }
      if ( $group_to_type{$group} eq 'cisco' ) {
        print CSCOLIST "$name,$read_community,$write_community,\n";
        print CSCOIPLIST "$address,$read_community,$write_community,\n";
      }
      $name = "";
      $group = "";
      $address = "";
      $read_community = "";
      $write_community = "";
    }
  }
  close NODES;
#  unlink "/export/home/automan./nervecenter.node";
}
close CFGLIST;
close CSCOLIST;
close CSCOIPLIST;
`/usr/bin/mv /export/home/automan/configarch.tmp /var/tmp/configarch.hosts`;
`/usr/bin/mv /export/home/automan/ciscoworks.tmp /var/tmp/ciscoworks.hosts`;
`/usr/bin/mv /export/home/automan/ciscoworksip.tmp /var/tmp/ciscoworks.ip`;
`/usr/bin/cat /dev/null > /export/home/automan/configarch.tmp`;
`/usr/bin/cat /dev/null > /export/home/automan/ciscoworks.tmp`;
`/usr/bin/cat /dev/null > /export/home/automan/ciscoworksip.tmp`;
`/usr/bin/rm /export/home/automan/nervecenter.node`;
